Repository XPEHO/xpeapp_android, pull requests merged in 2025-04, with the labels that each got.

#8 feat(agendaPage): add the agenda page
  app/src/main/java/com/xpeho/xpeapp/enums/Screens.kt
  app/src/main/java/com/xpeho/xpeapp/ui/Navigation.kt
  app/src/main/java/com/xpeho/xpeapp/ui/Resources.kt
  app/src/main/java/com/xpeho/xpeapp/ui/components/agenda/AgendaBirthdayCard.kt
  app/src/main/java/com/xpeho/xpeapp/ui/components/agenda/AgendaCard.kt
  app/src/main/java/com/xpeho/xpeapp/ui/components/agenda/AgendaCardList.kt
  app/src/main/java/com/xpeho/xpeapp/ui/components/agenda/AgendaItem.kt
  app/src/main/java/com/xpeho/xpeapp/ui/components/layout/TagPillCustom.kt
  app/src/main/java/com/xpeho/xpeapp/ui/page/AgendaPage.kt
  app/src/main/java/com/xpeho/xpeapp/ui/page/HomePage.kt
  app/src/main/java/com/xpeho/xpeapp/ui/uiState/AgendaUiState.kt
  app/src/main/java/com/xpeho/xpeapp/ui/viewModel/agenda/AgendaViewModel.kt
  app/src/main/res/drawable/calendar.xml
  app/src/main/res/drawable/location.xml
Labels: enhancement :rocket:

#10 fix(tagPillAndSidebar): adding the tagPill lib and sidebar profil change
  app/build.gradle
  app/src/main/java/com/xpeho/xpeapp/ui/components/agenda/AgendaCard.kt
  app/src/main/java/com/xpeho/xpeapp/ui/components/layout/SidebarItemProfile.kt
  app/src/main/java/com/xpeho/xpeapp/ui/components/layout/TagPillCustom.kt
Labels: enhancement :rocket:

#12 chore(dependabot): configure dependabot
  .github/dependabot.yml
Labels: chore :construction_worker_man:

#18 fix(popUpAgendaFeature): remove and replace the pop up actually in pl…
  app/src/main/java/com/xpeho/xpeapp/ui/page/AgendaPage.kt
  app/src/main/java/com/xpeho/xpeapp/ui/page/HomePage.kt
Labels: bug :bug:

#20 fix(emailMandatory): remove the email mandatory in the entity
  app/src/main/java/com/xpeho/xpeapp/data/model/agenda/AgendaBirthday.kt
  app/src/main/java/com/xpeho/xpeapp/data/service/WordpressRepository.kt
  app/src/test/java/com/xpeho/xpeapp/data/WordpressRepositoryTest.kt
Labels: bug :bug:
